services:
  # FastAPI backend server
  api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      # Mount source code for hot reloading
      - ./local_server.py:/app/local_server.py
      - ./genres:/app/genres
      # Mount the dashboard_data directory to persist generated JSON files
      - ./dashboard_data:/app/dashboard_data
      # Mount the data directory for CSV uploads (optional, can be removed in production)
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Static file server for the frontend (simple nginx without proxying)
  frontend:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      # Mount the dashboard directory as the web root
      - ./dashboard:/usr/share/nginx/html/dashboard
      # Mount dashboard_data for local file access
      - ./dashboard_data:/usr/share/nginx/html/dashboard_data
      # Custom nginx config for URL routing
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    driver: bridge